### ISSUE TITLE
Can't load bun-utilities, no error

### ISSUE THREAD

**Issue by bugs181** [xHyroM/bun-utilities#15]
Having some issues loading bun-utilities. For example, spawn doesn't appear to be anything.

```js
const { spawn } = require('bun-utilities/spawn')
const child = spawn('tail', ['-f', 'access.log'])

TypeError: spawn is not a function. (In 'spawn("tail", ["-f", "access.log"])', 'spawn' is undefined)
```

And just to see if the module contains anything:
```js
const bu = require('bun-utilities/spawn')
console.log(bu)

{ exec: undefined, spawn: undefined, execAndDontWait: undefined, spawnAndDontWait: undefined }
```

Just to ensure the correct bindings were installed, I see the `node_modules/bun-utilities/bindings/bun-utilities.linux-x64-gnu.node` file.

FWIW: `nativeBinding` appears to be empty (although, this could be irrelevant).
```js
nativeBinding = require(nativeBindingPath)
console.log(nativeBinding)

{ }
```

System:
```zsh
$ bun --version
0.1.11
```

**Comment by xhyrom** [comment]
it looks like its issue with latest bun

**Comment by bugs181** [comment]
For tracking: https://github.com/oven-sh/bun/issues/1240

**Comment by bugs181** [comment]
Fixed in: https://github.com/oven-sh/bun/issues/1240
