### ISSUE TITLE
Cannot require module on M1 Pro

### ISSUE THREAD

**Issue by targetlucked69** [xHyroM/bun-utilities#5]
Running this snippet

```ts
import { exec } from 'bun-utilities'

const p = await exec(['echo', 'test']);
console.log(p.stdout)
```

Throws this error

```bash
bun-test on  master [✘!?] is 📦 v0.0.0 via  v18.4.0 
❯ bun ./test.ts
75 |           loadError = e
76 |         }
77 |         break
78 |       case 'arm64':
79 |         try {
80 |           nativeBinding = require('./bindings/bun-utilities.darwin-arm64.node')
                                     ^
 error: Cannot require module "./bindings/bun-utilities.darwin-arm64.node"
      at /Users/jeremy/tmp/bun-test/node_modules/bun-utilities/lib/index.mjs:80:34
      at /Users/jeremy/tmp/bun-test/node_modules/bun-utilities/lib/index.mjs:80:34
```

<img width="204" alt="Screen Shot 2022-07-15 at 10 03 34 AM" src="https://user-images.githubusercontent.com/72330740/179272932-e51ca49c-a44a-4557-8fbd-f5aa12f4cb27.png">

Bun version 0.1.4

**Comment by targetlucked69** [comment]
<img width="401" alt="Screen Shot 2022-07-15 at 1 36 13 PM" src="https://user-images.githubusercontent.com/72330740/179306865-bd089323-b20a-45f9-90eb-f13d9f6da91a.png">

Looks like it is missing `bun-utilities.darwin-arm64.node`

**Comment by xhyrom** [comment]
Thanks, I'll fix it tomorrow (UTC+1)

**Comment by xhyrom** [comment]
After https://github.com/xHyroM/bun-utilities/actions/runs/2680838236 it will be fixed

**Comment by xhyrom** [comment]
https://github.com/xHyroM/bun-utilities/runs/7368702401?check_suite_focus=true

**Comment by targetlucked69** [comment]
awesome @xHyroM ! thanks
