### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by targetlucked69** [xHyroM/bun-utilities#6]
Hi, not really an issue. Just want to know if there's any way to **ONLY** download binary for user's OS? 

I'm talking about this...

<img width="398" alt="Screen Shot 2022-07-16 at 8 41 25 PM" src="https://user-images.githubusercontent.com/72330740/179382890-33c8fb4f-b734-43d2-be70-b015340c9d74.png">

Thank you!

**Comment by xhyrom** [comment]
> Hi, not really an issue. Just want to know if there's any way to **ONLY** download binary for user's OS?
> 
> I'm talking about this...
> 
> <img alt="Screen Shot 2022-07-16 at 8 41 25 PM" width="398" src="https://user-images.githubusercontent.com/72330740/179382890-33c8fb4f-b734-43d2-be70-b015340c9d74.png">
> 
> Thank you!

Not at the moment. I had the option to make each (binding) package separately which I didn't want to do because it would unnecessarily create 11 more packages so I put everything in 1 for now because the files are not that big. But I plan to make it so that I will release a release on GitHub where all the bindings will be and they will be automatically downloaded in the package after start.

**Comment by xhyrom** [comment]
For now, you can delete other files.

**Comment by targetlucked69** [comment]
> For now, you can delete other files.

Gotcha. Thanks

**Comment by targetlucked69** [comment]
> But I plan to make it so that I will release a release on GitHub where all the bindings will be and they will be automatically downloaded in the package after start.

So the trick here is like create a script file, maybe a js file, that downloads the build based on user's platform after running `bun add bun-utilities`, right?

**Comment by xhyrom** [comment]
> > But I plan to make it so that I will release a release on GitHub where all the bindings will be and they will be automatically downloaded in the package after start.
> 
> So the trick here is like create a script file, maybe a js file, that downloads the build based on user's platform after running `bun add bun-utilities`, right?

I couldn't automate this since bun probably doesn't support `postinstall` so I'll make it delete unnecessary bindings when the program starts.
