### ISSUE TITLE
Node.js ESM does not work.

### ISSUE THREAD

**Issue by paperclover** [xHyroM/bun-utilities#7]
`require` is used inside of `index.mjs`, which makes it fail to load on node esm. I get that this is a bun-specific project, but it would still be nice to have it work on node, as it does seem to support it somewhat.

The following line can be used to get a `require` in a node esm setting, but this will break bun as it doesn't provide a `createRequire`:
```
const require = createRequire(import.meta.url);
```

**Comment by xhyrom** [comment]
It's not problem, I'll add require typeof check

**Comment by xhyrom** [comment]
https://github.com/xHyroM/bun-utilities/commit/a351499d7e787ab9fd83808e383708512f2d2973 you can try install .node files from GitHub actions artifacts

I'll release new version soon

**Comment by xhyrom** [comment]
Released in 0.2.0
